# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Add build os (and other options)
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    # Read the docs needs a couple packages not in the environment file
    pre_install:
      - conda install -y cmake compilers sphinx sphinxcontrib-bibtex
      - conda install sphinx_rtd_theme>=1.3

conda:
  environment: environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
